opam-version: "2.0"
maintainer: "Jane Street developers"
authors: ["Jane Street Group, LLC"]
homepage: "https://github.com/public-release-reloaded/testable_timeout"
bug-reports: "https://github.com/public-release-reloaded/testable_timeout/issues"
dev-repo: "git+https://github.com/public-release-reloaded/testable_timeout.git#v0.18_preview.130.100+614+reloaded"
doc: "https://ocaml.janestreet.com/ocaml-core/latest/doc/testable_timeout/index.html"
license: "MIT"
x-maintenance-intent: ["(latest)"]
build: [
  ["dune" "build" "-p" name "-j" jobs]
]
depends: [
  "ocaml" {>= "5.5.0"}
  "async_kernel"
  "core"
  "ppx_jane"
  "dune"            {>= "3.17.0"}
  "js_of_ocaml-ppx" {>= "6.0.0"}
]
available: arch != "x86_32"
synopsis: "An API like the browser's setTimeout, but driven by an overridable async time source."
description: "
An API like the browser's setTimeout, but driven by an overridable async time source.
"
